- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- setup.py
* update alpha-related material to be beta like
* added other missing plugin updates
* convert readme to markdown
make same updates as from ape
check for other missing updates (standardize)
PR review
> chore: prep plugin for beta release

- .pre-commit-config.yaml
- ape_hardhat/exceptions.py
- ape_hardhat/process.py
- ape_hardhat/providers.py
- hardhat.config.js
- pyproject.toml
- setup.py
- tests/conftest.py
- tests/test_hardhat.py
Added mine and set_timestamp
fixes: #
added both functions to HardhatProvider
run tests
> feat: add mine and set timestamp methods

- ape_hardhat/providers.py
Updates to typing to support https://github.com/ApeWorX/ape/pull/594
> refactor: use correct type to support `unlock_account` feature

- README.md
- ape_hardhat/providers.py
- setup.py
- tests/conftest.py
- tests/test_hardhat.py
Added `get_transaction_trace()` to return EVM `TraceFrames` from hardhat's `debug_traceTransaction` method.
fixes: # https://github.com/ApeWorX/ape-hardhat/issues/41
> feat: add transaction trace iterator

- .github/workflows/test.yaml
- ape_hardhat/providers.py
- pyproject.toml
- setup.py
- tests/ape-config.yaml
- tests/conftest.py
- tests/test_fork_provider.py
> feat: support hardhat fork reset RCP

- README.md
- ape_hardhat/providers.py
* Convert RST links to MD links in README so that they work correctly
* Remove commented out code that shouldn't be there
Yes.
Make sure links works now.
> docs: fix links in readme

- README.md
- ape_hardhat/providers.py
- pyproject.toml
- setup.py
- tests/ape-config.yaml
- tests/conftest.py
- tests/test_fork_provider.py
- tests/test_provider.py
> feat: timeout config and bump default to 5 minutes for fork provider

- tests/conftest.py
- tests/test_fork_provider.py
- tests/test_transaction.py
Share contract fixtures in session scope to fix flaky tests
> test: session share of contract fixtures

- .github/ISSUE_TEMPLATE/bug.md
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- ape_hardhat/providers.py
- pyproject.toml
- setup.py
* Updates from template
* Remove really old deprecated code
* Fix mypy exclude setting using multiple files
> chore: template updates

- ape_hardhat/providers.py
- setup.py
- tests/test_fork_provider.py
fixes: #
https://github.com/ApeWorX/ape-hardhat/pull/83
(env var issue, had to open PR off upstream)
> fix: duplicate make_request method causing tracing to not work

- ape_hardhat/providers.py
- tests/ape-config.yaml
- tests/test_fork_provider.py
Remove references to ropsten, rinkeby, kovan
> fix: remove references to unsupported networks

- ape_hardhat/providers.py
> feat: use receipt cache when getting call tree

- ape_hardhat/provider.py
- tests/test_fork_provider.py
- tests/test_provider.py
blocking: # https://github.com/ApeWorX/ape/pull/1090
> feat: implement set_code

- ape_hardhat/__init__.py
> feat: include missing testnet forks

- ape_hardhat/provider.py
- setup.py
- tests/ape-config.yaml
- tests/conftest.py
- tests/expected_traces.py
- tests/test_gas_report.py
- tests/test_provider.py
- tests/test_trace.py
* Allows port to get set when doing `provider_settings={"port": num}`
* Refactors PoA check
* Fixes broken tests.
> fix: issue where port was not recognized in provider settings

- .pre-commit-config.yaml
- ape_hardhat/__init__.py
- ape_hardhat/provider.py
- setup.py
- tests/conftest.py
- tests/expected_traces.py
- tests/test_fork_provider.py
- tests/test_provider.py
- tests/test_trace.py
Refactorings from provider gas workings, nothing serious
> fix: subtract base gas from root level gas in call tree node

- ape_hardhat/__init__.py
- setup.cfg
added Optimism provider
fixes: APE-477
> feat: Add optimism

- .github/workflows/commit.yaml
Missing v for the action version
> fix: commit yaml

- ape_hardhat/provider.py
- setup.py
- tests/ape-config.yaml
- tests/test_fork_provider.py
- tests/test_provider.py
polygon poa detection was failing for some reason
check first and last block
> fix: PoA web3 middleware issue for Polygon networks [APE-789]

- ape_hardhat/provider.py
> perf: save a request [APE-792]

- ape_hardhat/__init__.py
Adds Gnosis chain.
Append  gnosis to  provider list
> feat: add gnosis for forking [APE-1023]

- .github/workflows/commit.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- README.md
- pyproject.toml
- setup.py
> feat: python 3.11 support [APE-1047]

- tests/test_gas_report.py
fixes a test that broke from lastest release
no actual breakage, just the test needed to be updated and is causing other PRs to fail
> test: fix test [APE-1108]

- ape_hardhat/provider.py
- tests/test_provider.py
> fix: auto regression [APE-1118]

- ape_hardhat/provider.py
- tests/test_provider.py
> fix: hardfork [APE-1214]

- ape_hardhat/provider.py
- setup.py
- tests/ape-config.yaml
- tests/conftest.py
> refactor: updates from latest ape release [APE-1516]

- ape_hardhat/__init__.py
Update the init file to incorporate base
> feat: add Base support 

- .github/workflows/codeql.yml
- .github/workflows/commit.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- setup.py
> feat: python 3.12 support

- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
- setup.py
also checking if the plugin works in CI because having issues locally.
> chore: upgrade lint dependencies

- .github/workflows/test.yaml
- .gitignore
- ape_hardhat/provider.py
- package-lock.json
- package.json
- tests/expected_traces.py
- tests/test_fork_provider.py
package.json needed here.
else running tests locally wasnt working in a fresh env
> test: in some envs, tests would not run because HH was not installed in the expected path

- .pre-commit-config.yaml
- ape_hardhat/__init__.py
- pyproject.toml
- setup.py
> chore: update deps and exposes HardhatForkProvider in library

- ape_hardhat/provider.py
- package-lock.json
- package.json
- setup.py
> feat: support web3.py 7.0 dependencies
