ApeWorX/ape-hardhat

ape_hardhat/__init__.py
ape_hardhat/providers.py
tests/test_hardhat.py

Added Windows support for the Hardhat network provider.
See https://github.com/ApeWorX/ape/issues/91#issuecomment-932458267 for steps on installing Ape on Windows. Once I got that to work, all that was needed was a small amount of OS-specific code to manage the Hardhat process on Windows.
No CI support yet (blocked by https://github.com/ApeWorX/ape/issues/91) but the test suite is passing locally for me:
```
PS C:\Users\orayo\Documents\steve\ape-hardhat> ..\ape-env\Scripts\pytest.exe
=== test session starts ===
platform win32 -- Python 3.8.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\orayo\Documents\steve\ape-hardhat, configfile: pytest.ini
plugins: hypothesis-6.23.0, cov-2.12.1, forked-1.3.0, xdist-2.4.0, web3-5.23.1
gw0 [17] / gw1 [17] / gw2 [17] / gw3 [17] …
```

feat: Windows support

---

.github/workflows/test.yaml
ape_hardhat/providers.py
setup.py

Related issue: #3 
Upgraded to eth-ape==0.1.0a24 for the logger change, then replaced all the print statements with calls to the logger.
I also added `--exclude=build` to the mypy CI job. I guess an unpinned dependency is now upgrading in CI (maybe setuptools?) and as part of the install step it leaves behind a `build` folder for the top level ape_hardhat project, which causes mypy to fail:
```
build/lib/ape_hardhat/__init__.py: error: Duplicate module named "ape_hardhat" (also at "./ape_hardhat/__init__.py")
build/lib/ape_hardhat/__init__.py: note: Are you missing an __init__.py? Alternatively, consider using --exclude to avoid checking one of them.
```
I couldn't reproduce this behavior locally with the same commands.
Running `ape console` is now silent, while running `ape console …

chore: replace print statements with debug logging

---

.pre-commit-config.yaml
ape_hardhat/providers.py
hardhat.config.js
pyproject.toml
pytest.ini
setup.py
tests/conftest.py
tests/test_hardhat.py

fixes: #10 
fixes: #8
Get hardhat off ape http (now called ape geth)
Note: will require another ape release with the PR below merged in
Use base provider from https://github.com/ApeWorX/ape/pull/231
Checkout PR above and run run some tests / scripts and stuff

feat: upgrade and support latest ape

---

README.rst
ape_hardhat/exceptions.py
ape_hardhat/process.py
ape_hardhat/providers.py
tests/test_hardhat.py

fixes: #8
fixes #5 
Before, hardhat always chose an unpredictable, random port.
Now, it will try 8545 first (for provider consistency's sake). If hardhat is already running on that port, it will use that hardhat, otherwise it will do like it did before and pick the random ephemeral port.
* Refactored out all process related stuff to its own module `process.py` which made it easy to add new features to.
**This will also make my hardhat-fork PR super easy to digest!**
Notice it used 8545 now!
Notice when 8545 is already with a hardhat, it connects to it that way (without process management)
Notice that when a user configures a specific port to use, and that port also has a hardhat already running, it connect to without process management.

feat: attempt to use port 8545 before picking a random port

---

README.rst
ape_hardhat/__init__.py
ape_hardhat/process.py
ape_hardhat/providers.py
setup.py

Adds a new provider to `mainnet-fork` network that is for using the `--fork` CLI arg in your hardhat node.
Subclass the provider and yield it from the plugin registration.
The subclass creates the `HardhatProcess` class a little differently, to include the `--fork` parameter.
Use https://github.com/ApeWorX/ape-infura/pull/13 as your upstream provider
Then, check and see what the block number is from web3! (it should be the latest from mainnet)
Also try commenting out bits of the config file to make sure it uses the default provider (`geth` in most people's cases).

feat: MainnetForkProvider

---

README.rst

Now that alchemy is released, we should reference that one instead, as its the community preferred upstream provider

docs: change example to reference alchemy

---

setup.py

Just realized this required ape beta 4 to work because it imports `SnapshotID`.
Tested on its `0.1.0b3` and realized it didn't work so bumped it to `0.1.0b4`.
Not really applicable as the last PR already made sure it worked on `b4`.

fix: bump ape pin to at least 0.1.0b4

---

ape_hardhat/__init__.py
ape_hardhat/providers.py
setup.py
tests/conftest.py

fixes: #18 
By checking the block number. Is there an easier way???
Start hardhat node process in your project
```bash
npx hardhat node
```
In another shell, try running mainnet fork hardhat node via ape:
```bash
ape console --network ::hardhat
```
It should say this:
```
INFO: Connecting to existing Hardhat node at port '8545'.
ERROR: (HardhatProviderError) Attempted to connect Hardhat Mainnet fork provider to different network than upstream. Stop or restart your Hardhat node in Mainnet fork mode to use this provider.
```

feat: raise error when trying to connect fork mode to non-fork node provider

---

ape_hardhat/__init__.py
ape_hardhat/providers.py

This PR allows supporting the `ape-fantom` plugin, when installed. If it is not installed, there is no adverse effects to the plugin
Added two lines
Check `ape networks list` with and without `ape-fantom` installed

feat: add support for fantom networks

---

ape_hardhat/providers.py
tests/conftest.py
tests/test_hardhat.py
tests/test_provider.py
tests/test_transaction.py

This fixes an issue raised in ape: https://github.com/ApeWorX/ape/issues/646
Check if not None before trying to conver.
Error should be the normal SignatureError.
See tests added!

fix: don't convert address if None

---

ape_hardhat/providers.py
tests/conftest.py
tests/test_fork_provider.py
tests/test_transaction.py

fixes: https://github.com/ApeWorX/ape-hardhat/issues/38
fixes: https://github.com/ApeWorX/ape/issues/606
detect chainID for transaction and if it is not self.chain_id then set it to self.chain_id and set the gas for transactions to zero

fix: contract impersonated transactions fail with incorrect chainID

---

ape_hardhat/providers.py
tests/test_provider.py

Makes severe speed improvements by avoiding Attr dicts from web3.py middleware and handling our own request validation logic. (Thank you @banteg for the suggestions)
Additionally, uses hardhat_mine RPC instead of evm_mine for performance improvements when mining a lot.

feat: handle our own request validation

---

setup.py

updated pins in setup.py for ape and alchemy
updated setup.py
github checks and pytest

chore: update ape-hardhat pins for v0.4.0

---

ape_hardhat/providers.py
tests/test_fork_provider.py

new feature: add parameter new_block_number to reset_fork(), so blocknumber could be switched during execution
Draft PR for this discord thread: https://discord.com/channels/922917176040640612/954593641970696292/1001008312076226580
new feature: add parameter new_block_number to reset_fork(), so blocknumber could be switched during execution

feat:  add parameter block_number to reset_fork(), so blocknumber could be switched during execution

---

ape_hardhat/providers.py
setup.py

This is needed as a companion to https://github.com/ApeWorX/ape/pull/1082 since the plugin uses ape's web3 dependency

fix: update web3 isConnected()

---

ape_hardhat/providers.py
tests/test_fork_provider.py
tests/test_provider.py

Adds tests for `get_receipt()` because I am having issues with `receiver` missing sometimes and am trying to figure out why. No luck yet, but having these tests would help me rule those things out faster.

test: test `get_receipt()`

---

.pre-commit-config.yaml
ape_hardhat/provider.py
pyproject.toml
setup.py
tests/ape-config.yaml
tests/data/python/pytest_tests.py
tests/expected_traces.py
tests/test_trace_pytest.py

* Adds missing test that I thought I had added and fixes some thing there
* Adds new tests for the `--gas-exclude` flag and `ape: test: gas` config stuff you can do by ignoring contracts and methods and such.

test: add tracing pytester tests

---

.pre-commit-config.yaml
README.md
ape_hardhat/provider.py
setup.py
tests/conftest.py
tests/test_fork_provider.py
tests/test_provider.py

Updated `HardhatForkProvider` to use `--no-deploy` when running `hardhat node --fork [...]` when the `hardhat-deploy` plugin is installed to prevent contract deployments from being automatically run.  
- `HardhatProvider` now loads `package.json` and reads the installed Hardhat plugins (assuming `hardhat-` package prefixes)
- If `enable_hardhat_deployments` is not set (or set to false), and the `hardhat-deploy` plugin is installed, it will add `--no-deploy` option to the `hardhat node [...]`
```bash
pytest
```

perf: adds --no-deploy (when appropriate) to hardhat fork command

---

ape_hardhat/provider.py
setup.py

chore: delete hack

---

ape_hardhat/provider.py

fix import, helps upgrade to 6.0 but can merge whenever
we should have importing this way all along, so not really a breaking change

fix: correct import statement of we3 TxParams [APE-764]

---

ape_hardhat/provider.py
setup.py

we had this check in before to handle both but now we can just handle web3.py >= 6.0.0
must wait for after https://github.com/ApeWorX/ape/pull/1361

chore: delete unneeded code from web3.py 6 upgrade [APE-765]

---

ape_hardhat/provider.py
tests/conftest.py
tests/test_fork_provider.py
tests/test_provider.py

fixes: #141 
Fixes: APE-910
* Track if seemingly not installed right
* If times out and was not installed right, show custom error
The reason I made it still attempt is because there are situations where it will still work, such as when using subprocess stuff.
* Go to a project where Hardhat is not yet installed.
* Do `ape console --network etheruem:local:hardhat
* Wait for it to fail
* Notice the custom error.

fix: issue where wouldn't show correct not-installed error [APE-918]

---

ape_hardhat/provider.py
tests/test_provider.py

Fixed critical issue preventing any trace related feature from working when the sender was impersonated.
note you may need to use my ape-vyper and ape coverage PRs to properly test that because of other unrelated fixes currently only present there
* get tx hash from the error message
* attempt calling eth_getTransactionReceipt before super() which will do the waiting unnecessarily and the waiting for some reason never ends no matter what, no matter required confs are or timeout or anything... so whatever, have to bypass it i guess tho maybe im just doing something stupid
* finally, use that receipt as the `txn=` kwarg when crafting the vm error (which thankfully is allowed and welcomed in core ape framework).
now all the tracing stuff should work.
it was a pain tho and i dont like …

fix: allow getting traces when sender is impersonated [APE-971]

---

ape_hardhat/provider.py
tests/test_provider.py

when using hardhat, the panic code can be extracted from the vm err but it is a bit branded (no prefix and other stuff around it etc).
this change allows it to work with ape-solidity for enrichment
have to use this PR tho: https://github.com/ApeWorX/ape-solidity/pull/99

feat: allow to work with Solidity compiler enrichment [APE-995]

---

ape_hardhat/provider.py
setup.py
tests/test_gas_report.py

hardhat doesnt offer a way to trace calls. however, we can still track func hit counts. this is great because auto-getters dont have source lines anyway. therefore, we can still get those counted in the coverage report.
tests needed

feat: increment function hit count for call coverage [APE-1122]

---

ape_hardhat/provider.py
tests/conftest.py
tests/test_provider.py

im not sure how this never raised before, but it is now...
plugin is unusable because the auto-generated config causes configuration errors in hardhat and the node never launches.
they must have added more validation recently or something, because really not sure how this went unnoticed, the tests wouldnt even pass. no node would start.
additionally, fixed other things we found in foundry related to remote host connections
put config in right spot

fix: issue causing entire plugin to no longer function [APE-1207]

---

ape_hardhat/__init__.py

Adds sepolia support to hardhat
fixes: 
updating the init file
`ape networks list` returns sepolia under hardhat

feat: add sepolia + add comment to remove goerli

---

.github/workflows/test.yaml

Updates node version in CI to match minimum supported by hardhat.

test(ci): updates CI tests to use node v18 to match hardhat requirements

---

ape_hardhat/provider.py

Shows call trace on transaction revert.
Ref: https://github.com/ApeWorX/ape/issues/1945

feat: show call trace on transaction revert

---

.github/workflows/draft.yaml

Updates release-drafter to v6.  Looke like probably due to Nodejs being deprecated on the platform?

fix(devops): update release-drafter to v6

---

ape_hardhat/__init__.py
tests/ape-config.yaml
tests/conftest.py
tests/test_fork_provider.py
tests/test_provider.py

https://blog.ethereum.org/2023/11/30/goerli-lts-update
https://www.alchemy.com/blog/goerli-faucet-deprecation
Goerli support on all networks is ending soon:
- February 16th - [Base Goerli](https://www.alchemy.com/blog/base-goerli-testnet-deprecation)
- March 7th - [Optimism Goerli](https://www.alchemy.com/blog/optimism-goerli-testnet-deprecation)
- March 18th - [Arbitrum Goerli](https://www.alchemy.com/blog/arbitrum-goerli-testnet-deprecation)
- April 1st - [Ethereum Goerli](https://www.alchemy.com/blog/ethereum-goerli-testnet-deprecation)
- April 6th - [Polygon zkEVM Goerli](https://www.alchemy.com/blog/polygon-zkevm-cardona-is-live)
- April 11th - [Starknet Goerli](https://www.alchemy.com/blog/starknet-sepolia-is-live)
- April 13th - [Polygon …

refactor: remove goerli

---

.github/workflows/test.yaml
.gitignore
.pre-commit-config.yaml
README.md
ape-config.yaml
ape_hardhat/provider.py
pyproject.toml
setup.py
tests/ape-config.yaml
tests/conftest.py
tests/expected_traces.py
tests/test_fork_provider.py
tests/test_gas_report.py
tests/test_provider.py
tests/test_trace.py

feat: Upgrade to Ape 0.8

---

ape-config.yaml
ape_hardhat/provider.py
setup.py
tests/test_provider.py

requires https://github.com/ApeWorX/ape/pull/2173
connect to hh and check your initial bal on a dev acct

feat: honor `balance` config for test accounts initial balance

---

.pre-commit-config.yaml
ape_hardhat/provider.py
setup.py
tests/test_provider.py

feat: support `raise_on_revert=False` for sending calls and transactions

---

setup.py

should make the docs build with correct assets now

fix: use sphinx-ape release

---

ape_hardhat/__init__.py
setup.cfg

Before:
```
In [1]: %time import ape_hardhat
CPU times: user 1.17 s, sys: 152 ms, total: 1.33 s
Wall time: 1.36 s
```
After:
```
oIn [1]: %time import ape_hardhat
CPU times: user 8.23 ms, sys: 3.43 ms, total: 11.7 ms
Wall time: 11.5 ms
```

perf: plugin load time

---

pyproject.toml
setup.py

fix: setuptools version pin in setup
